# Generated by Django 5.1.2 on 2025-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crée le ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['ref'],
            },
        ),
    ]
