# Generated by Django 5.1.2 on 2025-11-04 10:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email')),
                ('type_client', models.CharField(choices=[('pro', 'Professionnel'), ('part', 'Particulier')], default='pro', max_length=4, verbose_name='Type de client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crée le ')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('validée', 'Validée'), ('livrée', 'Livrée'), ('annulée', 'Annulée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4, verbose_name='TVA')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande', to='stocks.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'unique_together': {('commande', 'produit')},
            },
        ),
    ]
